version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db_pgadmin
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - db_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@spr.com
      PGADMIN_DEFAULT_PASSWORD: root@spr
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
  db_data:
